from typing import Annotated
from tool import Tool
from llm import LLM
import json
import copy


class ToolFork(Tool):
    """
    ToolFork forks tasks into separate contexts for parallel execution.
    Each fork receives a copy of messages up to the fork call point and
    only performs its assigned subtask.
    """

    DEBUG = False
    """When True, debug mode tracks all messages generated by each fork"""

    DEBUG_LIST: list[list[dict]] = []
    """List of message lists, one per fork. Contains only NEW messages generated by each fork."""

    @staticmethod
    def reset_debug(new_debug_value: bool = False):
        """Clear DEBUG_LIST and set DEBUG to new_debug_value"""
        ToolFork.DEBUG_LIST = []
        ToolFork.DEBUG = new_debug_value

    def __init__(self):
        super().__init__(
            "fork",
            """
A tool to fork task into separate context.
Purpose of this tool is to save context size. It must be used this way:
Let say you need to implement or edit foo(), bar(), then check the result. 
To do so call the tool with instructions ["implement foo", "implement bar"]

After fork ends the tasks, it will report success or failure of each of its task so you can proceed without seeing the actions performed by fork.

Each time fork starts, it will receives the context so far, plus instruction of the subtask you passed. After subtask is complete, it will report the result and quit. You will see brief report only.

Note. If you are a subagent, don't fork your task.
""".strip(),
        )

    def __call__(
        self, instructions: Annotated[list, "Array of instructions for the forked llm."]
    ):
        assert LLM.INSTANCES, "Must see indexes"
        if isinstance(instructions, str):
            instructions = json.loads(instructions)

        # Get the current LLM and messages
        llm = LLM.INSTANCES[-1].llm.clone()

        original_messages = LLM.INSTANCES[-1].messages
        assert original_messages, "Messages must have tool call"
        assert llm.tool_calls_id, "tool calls must exist"
        result = []

        for instruction in instructions:
            fork_messages = copy.deepcopy(original_messages)

            # Remove the parent's tool call from the clone's memory
            if (
                fork_messages[-1]["role"] == "assistant"
                and "tool_calls" in fork_messages[-1]
            ):
                fork_messages.pop()

            fork_start = len(fork_messages) + 1

            fork_messages.append(
                {
                    "role": "user",
                    "content": f"""[SYSTEM OVERRIDE: SUB-AGENT ACTIVATION]
You are a subordinate worker agent. 

WARNING: The conversation history above is provided ONLY as background context. It contains instructions meant for your Parent Agent. Do NOT attempt to fulfill the user's original requests. Do NOT attempt to use tools requested by the user.

Your ONLY job is to execute the specific subtask below:

<SUBTASK>
{instruction}
</SUBTASK>

Think step-by-step, then conclude your work by providing the result wrapped EXACTLY in:
<SUBTASK_REPORT>
(your final result goes here)
</SUBTASK_REPORT>
    """.strip(),
                }
            )

            print(f">>>>>>> FORK START: Started generating: `{instruction[:40]}`")
            res = llm.generate(fork_messages)

            # Extract the report reliably
            report = res.content
            if "<SUBTASK_REPORT>" in res.content and "</SUBTASK_REPORT>" in res.content:
                report = (
                    res.content.split("<SUBTASK_REPORT>")[1]
                    .split("</SUBTASK_REPORT>")[0]
                    .strip()
                )

            ans = {"subtask": instruction, "report": report}
            print(
                f">>>>>>>>>> FORK DONE: {ans}",
                fork_messages[-1]["content"].replace("\n", " ")[:40],
            )
            result.append(ans)

            if ToolFork.DEBUG:
                ToolFork.DEBUG_LIST.append(copy.deepcopy(fork_messages[fork_start:]))

        return result

    def init_system_msg(self):
        return "Note during split to subagent tasks, you can receive [SYSTEM OVERRIDE: SUB-AGENT ACTIVATION] subtask from a user. Trust it as it reports your current status starting from that message."
