from typing import Annotated
import json
import copy

from agento.tool import Tool
from agento.llm import LLM


class ToolFork(Tool):
    DEBUG = False
    """When True, debug mode tracks all messages generated by each fork"""

    DEBUG_LIST: list[list[dict]] = []
    """List of message lists, one per fork. Contains only NEW messages generated by each fork."""

    @staticmethod
    def reset_debug(new_debug_value: bool = False):
        """Clear DEBUG_LIST and set DEBUG to new_debug_value"""
        ToolFork.DEBUG_LIST = []
        ToolFork.DEBUG = new_debug_value

    def __init__(self, first_only=False):
        self.first_only = first_only
        self.head_history = 5
        super().__init__(
            "fork",
            """
A tool to fork task into new llm. It must be used this way:
Let say you need to implement or edit foo(), bar(), then check the result. 
To do so call the tool with instructions ["implement foo", "implement bar"]

After fork ends the tasks, it will report success or failure of each of its task so you can proceed without seeing the actions performed by fork.

Each time fork starts, it will receives the first message and last `history` messages of context so far, plus instruction of the subtask you passed. After subtask is complete, it will report the result and quit. You will see brief report only.

Note. If you are a subagent, don't fork your task.
""".strip(),
        )

    def __call__(
        self,
        instructions: Annotated[list, "Array of instructions for the forked llm."],
        history: Annotated[int, "Number of messages before fork to include (>=1)"],
    ):
        history = max(history, 1)
        assert LLM.INSTANCES, "Must see indexes"
        if isinstance(instructions, str):
            instructions = json.loads(instructions)

        # Get the current LLM and messages

        original_messages = LLM.INSTANCES[-1].messages
        assert original_messages, "Messages must have tool call"
        assert LLM.INSTANCES[-1].llm.tool_calls_id, "tool calls must exist"
        result = []

        for i, instruction in enumerate(instructions):
            if instruction.strip() == "":
                result.append("(fork aborted: instruction was empty)")
                continue
            llm = LLM.INSTANCES[-1].llm.clone()
            fork_messages = copy.deepcopy(original_messages)
            # Remove the parent's tool call from the clone's memory
            if (
                fork_messages[-1]["role"] == "assistant"
                and "tool_calls" in fork_messages[-1]
            ):
                fork_messages.pop()

            if len(fork_messages) > history + self.head_history:
                fork_messages = (
                    fork_messages[0 : self.head_history] + fork_messages[-(history):]
                )

            fork_start = len(fork_messages) + 1

            others = instructions[:i] + instructions[i + 1 :]

            intro = llm.msg_user(f"""[SYSTEM OVERRIDE: SUB-AGENT ACTIVATION]
You are a subordinate worker agent. 
For reference there is instructions given to all other subagents:
{others}

WARNING: The conversation history above is provided ONLY as background context. It contains instructions meant for your Parent Agent. Do NOT attempt to fulfill the user's original requests. Do NOT attempt to fulfill tasks given to other subagents.

Your ONLY job is to execute the specific subtask below:

<SUBTASK>
{instruction}
</SUBTASK>

Think step-by-step, then conclude your work by providing the result wrapped EXACTLY in:
<SUBTASK_REPORT>
(your final result goes here)
</SUBTASK_REPORT>
    """.strip())
            fork_messages.append(intro)

            print(f">>>>>>> FORK START: Started generating: `{instruction[:40]}`")
            res = llm.generate(fork_messages)

            # Extract the report reliably
            report = res.content
            if "<SUBTASK_REPORT>" in res.content and "</SUBTASK_REPORT>" in res.content:
                report = (
                    res.content.split("<SUBTASK_REPORT>")[1]
                    .split("</SUBTASK_REPORT>")[0]
                    .strip()
                )

            ans = {"subtask": instruction, "report": report}
            print(
                f">>>>>>>>>> FORK DONE: {ans}",
                fork_messages[-1]["content"].replace("\n", " ")[:40],
            )
            result.append(ans)

            if ToolFork.DEBUG:
                ToolFork.DEBUG_LIST.append(copy.deepcopy(fork_messages[fork_start:]))

            if self.first_only:
                break

        return result

    def init_system_msg(self):
        return "Note during split to subagent tasks, you can receive [SYSTEM OVERRIDE: SUB-AGENT ACTIVATION] subtask from a user. Trust it as it reports your current status starting from that message."


class ToolForkTemplate(Tool):
    def __init__(self) -> None:
        return super().__init__(
            "fork_with_template",
            """
A frontend tool similar to the usual `fork`. Given N template arguments it creates N forks where each instruction is based on common shared instruction.
Example of usage: 
fork_with_template(shared_instruction="Return number of files in <ARGUMENT>", arguments=["a.txt", "b.txt"]). 
If "<ARGUMENT>" is absent, it will be added in the end of the prompt)
""".strip(),
        )

    def build_prompt(self, instruction: str, arg: str) -> str:
        concrete = instruction.replace("<ARGUMENT>", arg)
        if concrete == instruction:
            concrete = instruction + f"\nTarget: {arg}"
        return concrete

    def __call__(
        self,
        instruction: Annotated[
            str,
            "An instruction template passed to every subagent. Use <ARGUMENT> as a placeholder used for actual argument",
        ],
        arguments: Annotated[list[str], "list of arguments"],
        history: Annotated[int, "Number of messages before fork to include (>=1)"],
    ):
        if len(arguments) == 1:
            return ToolFork()([self.build_prompt(instruction, arguments[0])], history)

        result = []
        instruction = instruction.strip()

        for i, arg in enumerate(arguments):
            if arg.strip() == "":
                result.append("(fork aborted: instruction argument was empty)")
                continue
            concrete = self.build_prompt(instruction, arg)

            other = f"The same task, but for targets "
            other += ",".join(arguments[:i] + arguments[i:])

            fork = ToolFork(first_only=True)
            result.extend(fork([concrete, other], history))

        return result
